# Generated by Django 5.0.3 on 2024-04-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio Detail'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='live_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
