# Generated by Django 5.0.3 on 2024-04-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('category', models.TextField(choices=[('WID', "What I've Done"), ('WIL', "What I've Learned")], default='WID', max_length=20)),
                ('content', models.TextField(max_length=500)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_log.skill')),
            ],
            options={
                'verbose_name_plural': 'Daily Entries',
            },
        ),
    ]
