# Generated by Django 5.0.3 on 2024-04-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_log', '0002_alter_dailyentry_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyentry',
            old_name='skill',
            new_name='skills',
        ),
    ]
