# Generated by Django 5.0.3 on 2024-04-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_log', '0004_alter_dailyentry_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(upload_to='skills/icons/'),
        ),
    ]
